apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment_analysis_megatron_proj
  labels:
    app: sentiment_analysis_megatron_proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment_analysis_megatron_proj
  template:
    metadata:
      labels:
        app: sentiment_analysis_megatron_proj
    spec:
      containers:
      - name: sentiment_analysis_megatron_proj
        image: 937206803011.dkr.ecr.us-east-1.amazonaws.com/sentiment_analysis_megatron_proj
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: sentiment_analysis_megatron_proj-service
spec:
  type: LoadBalancer
  selector:
    app: sentiment_analysis_megatron_proj
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000